[package]
name = "tmp-webview-test"
version = "0.1.0"
authors = ["Brandon Anzaldi <brandon@brandonanzaldi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.6", features = ["edge"] }