name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          #   artifact_name: tmp-webview-test
          #   asset_name: tmp-webview-test-linux-amd64
          - os: windows-latest
            artifact_name: tmp-webview-test.exe
            asset_name: tmp-webview-test-windows-amd64
          - os: macos-latest
            artifact_name: tmp-webview-test
            asset_name: tmp-webview-test-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}